- hosts: all
  gather_facts: no
  tasks:
    - name: install pip's docker 
      pip: 
        name: docker
      tags: req

    - name: copy .env
      template:
        src: templates/.env
        dest: /root/.env

    - name: start redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        env_file: /root/.env
      tags: web-start



      