- hosts: all
  gather_facts: no
  tasks:
    - name: install pip's docker 
      pip: 
        name: docker
      tags: req
        
    - name: start redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        env:
          REDMINE_DB_PASSWORD: '{{REDMINE_DB_PASSWORD}}'
          REDMINE_DB_POSTGRES: '{{REDMINE_DB_POSTGRES}}'
          REDMINE_DB_DATABASE: '{{REDMINE_DB_DATABASE}}'
          REDMINE_DB_USERNAME: '{{REDMINE_DB_USERNAME}}'
          REDMINE_DB_PORT: '{{REDMINE_DB_PORT}}'
      tags: web-start



      